# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(554, 392)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.scanBtn = QtWidgets.QPushButton(Form)
        self.scanBtn.setObjectName("scanBtn")
        self.gridLayout.addWidget(self.scanBtn, 0, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.selLabel = QtWidgets.QLabel(Form)
        self.selLabel.setObjectName("selLabel")
        self.verticalLayout.addWidget(self.selLabel)
        self.devCombo = QtWidgets.QComboBox(Form)
        self.devCombo.setObjectName("devCombo")
        self.verticalLayout.addWidget(self.devCombo)
        self.gridLayout.addLayout(self.verticalLayout, 0, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.delaySpin = QtWidgets.QSpinBox(Form)
        self.delaySpin.setMinimum(1)
        self.delaySpin.setMaximum(3600)
        self.delaySpin.setProperty("value", 1)
        self.delaySpin.setObjectName("delaySpin")
        self.horizontalLayout.addWidget(self.delaySpin)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.qLabel = QtWidgets.QLabel(Form)
        self.qLabel.setObjectName("qLabel")
        self.verticalLayout_2.addWidget(self.qLabel)
        self.qEdit = QtWidgets.QLineEdit(Form)
        self.qEdit.setObjectName("qEdit")
        self.verticalLayout_2.addWidget(self.qEdit)
        self.gridLayout.addLayout(self.verticalLayout_2, 1, 1, 1, 1)
        self.startBtn = QtWidgets.QPushButton(Form)
        self.startBtn.setObjectName("startBtn")
        self.gridLayout.addWidget(self.startBtn, 2, 0, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.aLabel = QtWidgets.QLabel(Form)
        self.aLabel.setObjectName("aLabel")
        self.verticalLayout_3.addWidget(self.aLabel)
        self.aEdit = QtWidgets.QLineEdit(Form)
        self.aEdit.setObjectName("aEdit")
        self.verticalLayout_3.addWidget(self.aEdit)
        self.gridLayout.addLayout(self.verticalLayout_3, 2, 1, 1, 1)
        self.stopBtn = QtWidgets.QPushButton(Form)
        self.stopBtn.setObjectName("stopBtn")
        self.gridLayout.addWidget(self.stopBtn, 3, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 172, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 4, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 172, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 4, 1, 1, 1)
        self.exitBtn = QtWidgets.QPushButton(Form)
        self.exitBtn.setObjectName("exitBtn")
        self.gridLayout.addWidget(self.exitBtn, 5, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.scanBtn.setText(_translate("Form", "Scan for instruments"))
        self.selLabel.setText(_translate("Form", "Select instrument"))
        self.label.setText(_translate("Form", "Timer delay (s)"))
        self.qLabel.setText(_translate("Form", "Query command"))
        self.startBtn.setText(_translate("Form", "Start "))
        self.aLabel.setText(_translate("Form", "Query answer"))
        self.stopBtn.setText(_translate("Form", "Stop"))
        self.exitBtn.setText(_translate("Form", "Exit"))
