# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'timing.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class timing_Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(174, 178)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label1 = QtWidgets.QLabel(Dialog)
        self.label1.setObjectName("label1")
        self.verticalLayout.addWidget(self.label1)
        self.delay1 = QtWidgets.QSpinBox(Dialog)
        self.delay1.setMinimum(20)
        self.delay1.setMaximum(100000)
        self.delay1.setObjectName("delay1")
        self.verticalLayout.addWidget(self.delay1)
        self.label2 = QtWidgets.QLabel(Dialog)
        self.label2.setObjectName("label2")
        self.verticalLayout.addWidget(self.label2)
        self.delay2 = QtWidgets.QSpinBox(Dialog)
        self.delay2.setMinimum(20)
        self.delay2.setMaximum(100000)
        self.delay2.setObjectName("delay2")
        self.verticalLayout.addWidget(self.delay2)
        self.label3 = QtWidgets.QLabel(Dialog)
        self.label3.setObjectName("label3")
        self.verticalLayout.addWidget(self.label3)
        self.nloops = QtWidgets.QSpinBox(Dialog)
        self.nloops.setMinimum(1)
        self.nloops.setMaximum(1000)
        self.nloops.setObjectName("nloops")
        self.verticalLayout.addWidget(self.nloops)
        self.label4 = QtWidgets.QLabel(Dialog)
        self.label4.setObjectName("label4")
        self.verticalLayout.addWidget(self.label4)
        self.chunk_size = QtWidgets.QSpinBox(Dialog)
        self.chunk_size.setMinimum(1)
        self.chunk_size.setMaximum(1000)
        self.chunk_size.setObjectName("chunk_size")
        self.verticalLayout.addWidget(self.chunk_size)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Timing settings"))
        self.label1.setText(_translate("Dialog", "Primary delay value (ms)"))
        self.label2.setText(_translate("Dialog", "Secondary delay value (sweep mode only, ms)"))
        self.label3.setText(_translate("Dialog", "Number of minor loops (sweep mode only)"))
        self.label4.setText(_translate("Dialog", "Data chunk size for writing to file"))
        
class timingDialog(QtWidgets.QDialog, timing_Ui_Dialog):
	def __init__(self):
		super(timingDialog, self).__init__()
		self.setupUi(self)
